# Generated by Django 4.2.2 on 2023-06-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=333, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
