# Generated by Django 4.2.2 on 2023-06-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='last_login',
        ),
    ]
